max_width = 120
chain_width = 120
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Off"
use_field_init_shorthand = true
match_block_trailing_comma = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true
imports_indent = "Block"
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
brace_style = "AlwaysNextLine"
enum_discrim_align_threshold = 30
format_code_in_doc_comments = true
doc_comment_code_block_width = 120
format_strings = true
hex_literal_case = "Upper"